name: ValueEdgeIntegration
# Events the integration should be triggered on
on:
  pull_request:
    types: [opened, edited, closed, reopened]
  workflow_run:
    # List of workflows to integrate with ValueEdge
    workflows: [CI Selenium Test GitHub Actions]
    types: [requested, completed]
# Node configuration for allowing HTTPS requests
env:
  NODE_TLS_REJECT_UNAUTHORIZED: 1
jobs:
  valueedge_integration_job:
    # List of runner tags
    runs-on: self-hosted
    name: ValueEdgeIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          path: '**/TEST*.xml'
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: 'artifacts/'
      - name: GitHub Actions ValueEdge Integration
        # Reference to our public GitHub action
        uses: MicroFocus/alm-octane-github-actions-integration@v23.3.0
        id: gitHubActionsIntegration
        # Config parameters for the integration
        with:
          # ValueEdge connection data
          octaneUrl: 'https://almoctane-ams.saas.microfocus.com/'
          octaneSharedSpace: 211010
          octaneWorkspace: 23004
          octaneClientId: ${{secrets.ALM_OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.ALM_OCTANE_CLIENT_SECRET}}
          # Automatically provided GitHub token
          githubToken: ${{secrets.GITHUB_TOKEN}}
          # The url that the CI Server in ValueEdge will point to
          serverBaseUrl: https://github.com/salvadorcamachogithub/SeleniumTestGitHubActions
          # Pattern for identifying JUnit style report files for test result injection in ValueEdge
          unitTestResultsGlobPattern: '**/TEST*.xml'